source 'https://rubygems.org'

gem 'rails', '@@Rails::VERSION::STRING@@'
gem 'mysql2'

gem 'sass-rails',   '~> 4.0.3'
gem 'compass-rails'
gem 'uglifier',     '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder',     '~> 2.0'

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

group :development do
  gem 'thin'
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller', platforms: [:mri_20]
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec', '~> 4.2.8'
  gem 'rb-fchange', require: false
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false
  gem 'rack-mini-profiler'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'quiet_assets'
  gem 'html2haml'
end

group :development, :test do
  gem 'debugger'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'rspec',       '~> 3.0.0.beta2'
  gem 'rspec-rails', '~> 3.0.0.beta2'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'faker'
  gem 'faker-japanese'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', require: false
  gem 'simplecov',        require: false
  gem 'simplecov-rcov',   require: false
end
